### ISSUE TITLE
Bug: Animations are causing the scrollbar to appear, which causes the UI to stutter

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/calendar-complete#17]
#### Desired Behavior

The app should animate without causing the scrollbars to appear in desktop view

#### Actual Behavior

Instead the app loads the scrollbars whenever an animation occurs in desktop mode, which causes the UI to stutter

#### Steps to Reproduce

1. Open app outside of mobile view
2. Click on any calendar day in the month or one of the month arrows at the top of the calendar
3. Note that the scrollbar is appearing briefly during the animation, which is resizing the viewport

## ✅ Task List

- [x] Identify the GSAP animations that are causing the bug
- [x] revise the 'from' values so that they are within the viewport
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
