### ISSUE TITLE
Refactor: Update to use fetch

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/calendar-complete#22]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [ ] ... 
- [ ] ...
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
