### ISSUE TITLE
Refactor: Update to use modules

### ISSUE THREAD

**Issue by josephtnguyen** [josephtnguyen/calendar-complete#23]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Update package.json to include webpack scripts.
- [x] Install webpack and webpack cli.
- [x] Test to see if scripts work.
- [ ] Move AJAX function to separate modules.
- [ ] Move event handlers to separate modules.
- [ ] Move general functions to separate modules.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
